List countryData = [
  { "Code": "1", "Country": "United States"},
  { "Code": "93", "Country": "Afghanistan"},
  { "Code": "355", "Country": "Albania"},
  { "Code": "213", "Country": "Algeria"},
  { "Code": "1.1", "Country": "American Samoa"},
  { "Code": "376", "Country": "Andorra"},
  { "Code": "244", "Country": "Angola"},
  { "Code": "1.2", "Country": "Anguilla"},
  { "Code": "672", "Country": "Antarctica"},
  { "Code": "1.3", "Country": "Antigua and Barbuda"},
  { "Code": "54", "Country": "Argentina"},
  { "Code": "374", "Country": "Armenia"},
  { "Code": "297", "Country": "Aruba"},
  { "Code": "61", "Country": "Australia"},
  { "Code": "43", "Country": "Austria"},
  { "Code": "994", "Country": "Azerbaidjan"},
  { "Code": "1.4", "Country": "Bahamas"},
  { "Code": "973", "Country": "Bahrain"},
  { "Code": "880", "Country": "Bangladesh"},
  { "Code": "1.5", "Country": "Barbados"},
  { "Code": "375", "Country": "Belarus"},
  { "Code": "32", "Country": "Belgium"},
  { "Code": "501", "Country": "Belize"},
  { "Code": "229", "Country": "Benin"},
  { "Code": "1.6", "Country": "Bermuda"},
  { "Code": "975", "Country": "Bhutan"},
  { "Code": "591", "Country": "Bolivia"},
  { "Code": "387", "Country": "Bosnia-Herzegovina"},
  { "Code": "267", "Country": "Botswana"},
  { "Code": "47.2", "Country": "Bouvet Island"},
  { "Code": "55", "Country": "Brazil"},
  { "Code": "246", "Country": "British Indian Ocean Territory"},
  { "Code": "673", "Country": "Brunei Darussalam"},
  { "Code": "359", "Country": "Bulgaria"},
  { "Code": "226", "Country": "Burkina Faso"},
  { "Code": "257", "Country": "Burundi"},
  { "Code": "855", "Country": "Cambodia"},
  { "Code": "237", "Country": "Cameroon"},
  { "Code": "1.7", "Country": "Canada"},
  { "Code": "238", "Country": "Cape Verde"},
  { "Code": "1.8", "Country": "Cayman Islands"},
  { "Code": "236", "Country": "Central African Republic"},
  { "Code": "235", "Country": "Chad"},
  { "Code": "56", "Country": "Chile"},
  { "Code": "86", "Country": "China"},
  { "Code": "61", "Country": "Christmas Island"},
  { "Code": "891", "Country": "Cocos (Keeling) Islands"},
  { "Code": "57", "Country": "Colombia"},
  { "Code": "269", "Country": "Comoros"},
  { "Code": "242", "Country": "Congo"},
  { "Code": "243", "Country": "Congo (Democratic Republic)"},
  { "Code": "682", "Country": "Cook Islands"},
  { "Code": "506", "Country": "Costa Rica"},
  { "Code": "385", "Country": "Croatia"},
  { "Code": "53", "Country": "Cuba"},
  { "Code": "357", "Country": "Cyprus"},
  { "Code": "420", "Country": "Czech Republic"},
  { "Code": "45", "Country": "Denmark"},
  { "Code": "253", "Country": "Djibouti"},
  { "Code": "1.9", "Country": "Dominica"},
  { "Code": "1.1", "Country": "Dominican Republic"},
  { "Code": "670", "Country": "East Timor"},
  { "Code": "593", "Country": "Ecuador"},
  { "Code": "20", "Country": "Egypt"},
  { "Code": "503", "Country": "El Salvador"},
  { "Code": "240", "Country": "Equatorial Guinea"},
  { "Code": "291", "Country": "Eritrea"},
  { "Code": "372", "Country": "Estonia"},
  { "Code": "251", "Country": "Ethiopia"},
  { "Code": "500", "Country": "Falkland Islands"},
  { "Code": "298", "Country": "Faroe Islands"},
  { "Code": "679", "Country": "Fiji"},
  { "Code": "358", "Country": "Finland"},
  { "Code": "33", "Country": "France"},
  { "Code": "33", "Country": "France (European Territory)"},
  { "Code": "594", "Country": "French Guiana"},
  { "Code": "260", "Country": "French Southern Territories"},
  { "Code": "241", "Country": "Gabon"},
  { "Code": "220", "Country": "Gambia"},
  { "Code": "995", "Country": "Georgia"},
  { "Code": "49", "Country": "Germany"},
  { "Code": "233", "Country": "Ghana"},
  { "Code": "350", "Country": "Gibraltar"},
  { "Code": "44.1", "Country": "Great Britain"},
  { "Code": "30", "Country": "Greece"},
  { "Code": "299", "Country": "Greenland"},
  { "Code": "1.11", "Country": "Grenada"},
  { "Code": "590", "Country": "Guadeloupe"},
  { "Code": "1.12", "Country": "Guam"},
  { "Code": "502", "Country": "Guatemala"},
  { "Code": "224", "Country": "Guinea"},
  { "Code": "245", "Country": "Guinea Bissau"},
  { "Code": "592", "Country": "Guyana"},
  { "Code": "509", "Country": "Haiti"},
  { "Code": "334", "Country": "Heard and McDonald Islands"},
  { "Code": "96", "Country": "Holy See (Vatican City State)"},
  { "Code": "379", "Country": "Honduras"},
  { "Code": "852", "Country": "Hong Kong"},
  { "Code": "36", "Country": "Hungary"},
  { "Code": "354", "Country": "Iceland"},
  { "Code": "91", "Country": "India"},
  { "Code": "62", "Country": "Indonesia"},
  { "Code": "98", "Country": "Iran"},
  { "Code": "964", "Country": "Iraq"},
  { "Code": "353", "Country": "Ireland"},
  { "Code": "972", "Country": "Israel"},
  { "Code": "39", "Country": "Italy"},
  { "Code": "225", "Country": "Ivory Coast (Cote D`Ivoire)"},
  { "Code": "1.13", "Country": "Jamaica"},
  { "Code": "81", "Country": "Japan"},
  { "Code": "962", "Country": "Jordan"},
  { "Code": "7.1", "Country": "Kazakhstan"},
  { "Code": "254", "Country": "Kenya"},
  { "Code": "686", "Country": "Kiribati"},
  { "Code": "965", "Country": "Kuwait"},
  { "Code": "996", "Country": "Kyrgyz Republic (Kyrgyzstan)"},
  { "Code": "856", "Country": "Laos"},
  { "Code": "371", "Country": "Latvia"},
  { "Code": "961", "Country": "Lebanon"},
  { "Code": "266", "Country": "Lesotho"},
  { "Code": "231", "Country": "Liberia"},
  { "Code": "218", "Country": "Libya"},
  { "Code": "423", "Country": "Liechtenstein"},
  { "Code": "370", "Country": "Lithuania"},
  { "Code": "352", "Country": "Luxembourg"},
  { "Code": "853", "Country": "Macau"},
  { "Code": "389", "Country": "Macedonia"},
  { "Code": "261", "Country": "Madagascar"},
  { "Code": "265", "Country": "Malawi"},
  { "Code": "60", "Country": "Malaysia"},
  { "Code": "960", "Country": "Maldives"},
  { "Code": "223", "Country": "Mali"},
  { "Code": "356", "Country": "Malta"},
  { "Code": "692", "Country": "Marshall Islands"},
  { "Code": "596", "Country": "Martinique"},
  { "Code": "222", "Country": "Mauritania"},
  { "Code": "230", "Country": "Mauritius"},
  { "Code": "262.1", "Country": "Mayotte"},
  { "Code": "52", "Country": "Mexico"},
  { "Code": "691", "Country": "Micronesia"},
  { "Code": "373", "Country": "Moldavia"},
  { "Code": "377", "Country": "Monaco"},
  { "Code": "976", "Country": "Mongolia"},
  { "Code": "1.14", "Country": "Releway"},
  { "Code": "212", "Country": "Morocco"},
  { "Code": "258", "Country": "Mozambique"},
  { "Code": "95", "Country": "Myanmar"},
  { "Code": "264", "Country": "Namibia"},
  { "Code": "674", "Country": "Nauru"},
  { "Code": "977", "Country": "Nepal"},
  { "Code": "31", "Country": "Netherlands"},
  { "Code": "599", "Country": "Netherlands Antilles"},
  { "Code": "687", "Country": "New Caledonia"},
  { "Code": "64", "Country": "New Zealand"},
  { "Code": "505", "Country": "Nicaragua"},
  { "Code": "227", "Country": "Niger"},
  { "Code": "234", "Country": "Nigeria"},
  { "Code": "683", "Country": "Niue"},
  { "Code": "159", "Country": "Norfolk Island"},
  { "Code": "850", "Country": "North Korea"},
  { "Code": "1.15", "Country": "Northern Mariana Islands"},
  { "Code": "47", "Country": "Norway"},
  { "Code": "968", "Country": "Oman"},
  { "Code": "92", "Country": "Pakistan"},
  { "Code": "680", "Country": "Palau"},
  { "Code": "507", "Country": "Panama"},
  { "Code": "675", "Country": "Papua New Guinea"},
  { "Code": "595", "Country": "Paraguay"},
  { "Code": "51", "Country": "Peru"},
  { "Code": "63", "Country": "Philippines"},
  { "Code": "64.1", "Country": "Pitcairn Island"},
  { "Code": "48", "Country": "Poland"},
  { "Code": "689", "Country": "Polynesia"},
  { "Code": "351", "Country": "Portugal"},
  { "Code": "1.16", "Country": "Puerto Rico"},
  { "Code": "974", "Country": "Qatar"},
  { "Code": "262", "Country": "Reunion"},
  { "Code": "40", "Country": "Romania"},
  { "Code": "7", "Country": "Russian Federation"},
  { "Code": "250", "Country": "Rwanda"},
  { "Code": "500.1", "Country": "S. Georgia & S. Sandwich Isls."},
  { "Code": "290", "Country": "Saint Helena"},
  { "Code": "1.17", "Country": "Saint Kitts & Nevis Anguilla"},
  { "Code": "1.18", "Country": "Saint Lucia"},
  { "Code": "508", "Country": "Saint Pierre and Miquelon"},
  { "Code": "1.19", "Country": "Saint Vincent & Grenadines"},
  { "Code": "685", "Country": "Samoa"},
  { "Code": "378", "Country": "San Marino"},
  { "Code": "239", "Country": "Sao Tome and Principe"},
  { "Code": "966", "Country": "Saudi Arabia"},
  { "Code": "221", "Country": "Senegal"},
  { "Code": "248", "Country": "Seychelles"},
  { "Code": "232", "Country": "Sierra Leone"},
  { "Code": "65", "Country": "Singapore"},
  { "Code": "421", "Country": "Slovak Republic"},
  { "Code": "386", "Country": "Slovenia"},
  { "Code": "677", "Country": "Solomon Islands"},
  { "Code": "252", "Country": "Somalia"},
  { "Code": "27", "Country": "South Africa"},
  { "Code": "82", "Country": "South Korea"},
  { "Code": "34", "Country": "Spain"},
  { "Code": "94", "Country": "Sri Lanka"},
  { "Code": "249", "Country": "Sudan"},
  { "Code": "597", "Country": "Suriname"},
  { "Code": "47.1", "Country": "Svalbard and Jan Mayen Islands"},
  { "Code": "268", "Country": "Swaziland"},
  { "Code": "46", "Country": "Sweden"},
  { "Code": "41", "Country": "Switzerland"},
  { "Code": "963", "Country": "Syria"},
  { "Code": "886", "Country": "Taiwan"},
  { "Code": "992", "Country": "Tajikistan"},
  { "Code": "255", "Country": "Tanzania"},
  { "Code": "66", "Country": "Thailand"},
  { "Code": "228", "Country": "Togo"},
  { "Code": "690", "Country": "Tokelau"},
  { "Code": "676", "Country": "Tonga"},
  { "Code": "1", "Country": "Trinidad and Tobago"},
  { "Code": "216", "Country": "Tunisia"},
  { "Code": "90", "Country": "Turkey"},
  { "Code": "993", "Country": "Turkmenistan"},
  { "Code": "1.2", "Country": "Turks and Caicos Islands"},
  { "Code": "668", "Country": "Tuvalu"},
  { "Code": "1.21", "Country": "USA Minor Outlying Islands"},
  { "Code": "256", "Country": "Uganda"},
  { "Code": "380", "Country": "Ukraine"},
  { "Code": "971", "Country": "United Arab Emirates"},
  { "Code": "44", "Country": "United Kingdom"},
  { "Code": "598", "Country": "Uruguay"},
  { "Code": "998", "Country": "Uzbekistan"},
  { "Code": "678", "Country": "Vanuatu"},
  { "Code": "58", "Country": "Venezuela"},
  { "Code": "84", "Country": "Vietnam"},
  { "Code": "1.22", "Country": "Virgin Islands (British)"},
  { "Code": "1.23", "Country": "Virgin Islands (USA)"},
  { "Code": "681", "Country": "Wallis and Futuna Islands"},
  { "Code": "212.1", "Country": "Western Sahara"},
  { "Code": "967", "Country": "Yemen"},
  { "Code": "381", "Country": "Yugoslavia"},
  { "Code": "243.1", "Country": "Zaire"},
  { "Code": "260", "Country": "Zambia"},
  { "Code": "263", "Country": "Zimbabwe"}
];
